services:
  - type: web
    name: safepill
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
